"""fix_token_expires_at_timezone

Revision ID: 46febd426f4b
Revises: 8aa7a58a0b78
Create Date: 2026-06-08 15:38:47.611107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46febd426f4b'
down_revision: Union[str, Sequence[str], None] = '8aa7a58a0b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
