"""fix_token_expires_at_timezone_x2

Revision ID: 4e41a946f5ae
Revises: 46febd426f4b
Create Date: 2026-06-08 15:40:49.052166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e41a946f5ae'
down_revision: Union[str, Sequence[str], None] = '46febd426f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
