"""add cascade delete to fk constraints

Revision ID: 6175b4f7613c
Revises: 470d06b0e879
Create Date: 2026-06-10 11:46:53.829899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6175b4f7613c'
down_revision: Union[str, Sequence[str], None] = '470d06b0e879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_task_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_workspace_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_parent_task_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('workspacemember_workspace_id_fkey'), 'workspacemember', type_='foreignkey')
    op.create_foreign_key(None, 'workspacemember', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspacemember', type_='foreignkey')
    op.create_foreign_key(op.f('workspacemember_workspace_id_fkey'), 'workspacemember', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_parent_task_id_fkey'), 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_workspace_id_fkey'), 'projects', 'workspace', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_task_id_fkey'), 'comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
